let mobiles = [
    {
      id: 1,
      name: "Samsung Galaxy S21",
      price: 49999,
      brand: "Samsung",
      image: "./imgs/product/1.jpeg",
      rating: 4.5,
    },
    {
      id: 2,
      name: "iPhone 14",
      price: 72999,
      brand: "Apple",
      image: "./imgs/product/2.jpeg",
      rating: 4.7,
    },
    {
      id: 3,
      name: "OnePlus 11R",
      price: 39999,
      brand: "OnePlus",
      image: "./imgs/product/3.jpeg",
      rating: 4.3,
    },
    {
      id: 4,
      name: "Realme Narzo 60",
      price: 16999,
      brand: "Realme",
      image: "./imgs/product/4.jpeg",
      rating: 4.2,
    },
    {
      id: 5,
      name: "Redmi Note 12",
      price: 18999,
      brand: "Redmi",
      image: "./imgs/product/5.jpeg",
      rating: 4.4,
    },
    {
      id: 6,
      name: "Motorola G73",
      price: 16999,
      brand: "Motorola",
      image: "./imgs/product/6.jpeg",
      rating: 4.0,
    },
    {
      id: 7,
      name: "Poco X5 Pro",
      price: 20999,
      brand: "Poco",
      image: "./imgs/product/7.jpeg",
      rating: 4.1,
    },
    {
      id: 8,
      name: "Vivo T2",
      price: 15499,
      brand: "Vivo",
      image: "./imgs/product/10.jpeg",
      rating: 4.2,
    },
    {
      id: 9,
      name: "Infinix Zero 5G",
      price: 12999,
      brand: "Infinix",
      image: "./imgs/product/11.jpeg",
      rating: 3.9,
    },
    {
      id: 10,
      name: "Lava Blaze 5G",
      price: 11499,
      brand: "Lava",
      image: "./imgs/product/19.jpeg",
      rating: 3.8,
    },
    {
      id: 11,
      name: "iQOO Z7",
      price: 17999,
      brand: "iQOO",
      image: "./imgs/product/28.jpeg",
      rating: 4.4,
    },
    {
      id: 12,
      name: "Nothing Phone (1)",
      price: 29999,
      brand: "Nothing",
      image: "./imgs/product/23.jpeg",
      rating: 4.5,
    },
    {
      id: 13,
      name: "Samsung Galaxy M13",
      price: 10999,
      brand: "Samsung",
      image: "./imgs/product/22.jpeg",
      rating: 4.1,
    },
    {
      id: 14,
      name: "Realme C55",
      price: 10499,
      brand: "Realme",
      image: "./imgs/product/21.jpeg",
      rating: 4.0,
    },
    {
      id: 15,
      name: "Redmi 12C",
      price: 9499,
      brand: "Redmi",
      image: "./imgs/product/20.jpeg",
      rating: 3.7,
    },
    {
      id: 16,
      name: "Vivo Y100",
      price: 23999,
      brand: "Vivo",
      image: "./imgs/product/18.jpeg",
      rating: 4.2,
    },
    {
      id: 17,
      name: "iPhone SE (2022)",
      price: 49999,
      brand: "Apple",
      image: "./imgs/product/19.jpeg",
      rating: 4.6,
    },
    {
      id: 18,
      name: "OnePlus Nord CE 3",
      price: 26999,
      brand: "OnePlus",
      image: "./imgs/product/15.jpeg",
      rating: 4.3,
    },
    {
      id: 19,
      name: "Moto Edge 40",
      price: 28999,
      brand: "Motorola",
      image: "./imgs/product/14.jpeg",
      rating: 4.5,
    },
    {
      id: 20,
      name: "Poco M4 Pro",
      price: 13999,
      brand: "Poco",
      image: "./imgs/product/13.jpeg",
      rating: 4.1,
    },
    {
        id: 21,
        name: "Vivo Y100",
        price: 23999,
        brand: "Vivo",
        image: "./imgs/product/12.jpeg",
        rating: 4.2,
      },
      {
        id: 22,
        name: "iPhone SE (2022)",
        price: 49999,
        brand: "Apple",
        image: "./imgs/product/25.jpeg",
        rating: 4.6,
      },
      {
        id: 23,
        name: "OnePlus Nord CE 3",
        price: 26999,
        brand: "OnePlus",
        image: "./imgs/product/24.jpeg",
        rating: 4.3,
      },
      {
        id: 24,
        name: "Moto Edge 40",
        price: 28999,
        brand: "Motorola",
        image: "./imgs/product/21.jpeg",
        rating: 4.5,
      },
      {
        id: 25,
        name: "Poco M4 Pro",
        price: 13999,
        brand: "Poco",
        image: "./imgs/product/17.jpeg",
        rating: 4.1,
      },
      {
        id: 26,
        name: "Samsung Galaxy S21",
        price: 49999,
        brand: "Samsung",
        image: "./imgs/product/1.jpeg",
        rating: 4.5,
      },
      {
        id: 27,
        name: "iPhone 14",
        price: 72999,
        brand: "Apple",
        image: "./imgs/product/2.jpeg",
        rating: 4.7,
      },
      {
        id: 28,
        name: "OnePlus 11R",
        price: 39999,
        brand: "OnePlus",
        image: "./imgs/product/3.jpeg",
        rating: 4.3,
      },
      {
        id: 29,
        name: "Realme Narzo 60",
        price: 16999,
        brand: "Realme",
        image: "./imgs/product/4.jpeg",
        rating: 4.2,
      },
      {
        id: 30,
        name: "Redmi Note 12",
        price: 18999,
        brand: "Redmi",
        image: "./imgs/product/5.jpeg",
        rating: 4.4,
      }
  ];

  let Mobile = document.getElementById("Mobile"); // Make sure this element exists

for (let data of mobiles) {
  Mobile.innerHTML += `
    <div class="mobile_box ">
      <img src="${data.image}" alt="${data.name}" />
      <h5>${data.name}</h5>
      <p><span>${data.rating}</span> ★ | Brand: ${data.brand}</p>
      <p>₹ ${data["price"]}</p>
    </div>
  `;
}

  